###
POST http://localhost:3000/api/threads
Content-Type: application/json

{
  "participants":""
}

###
POST http://localhost:3000/api/messages
Content-Type: application/json

{
  "threadId":"", 
  "userId":"", 
  "body":""
}
###
POST http://localhost:3000/api/messages/:threadId
Content-Type: application/json

{
  "threadId":""
}
